# Generated by Django 3.0.3 on 2020-05-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katalog',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='katalog',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='katalog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='katalog',
            name='updated',
        ),
    ]
