# Generated by Django 3.0.3 on 2020-05-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_auto_20200505_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podstawowy',
            name='kategoria',
        ),
        migrations.DeleteModel(
            name='darmowy',
        ),
        migrations.DeleteModel(
            name='podstawowy',
        ),
    ]
