# Generated by Django 3.0.3 on 2020-05-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_auto_20200505_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalog',
            name='slug',
        ),
    ]
