# Generated by Django 3.0.3 on 2020-05-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_auto_20200506_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
