# Generated by Django 3.0.3 on 2020-05-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0007_auto_20200510_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='katalog/%Y/%m/%d'),
        ),
    ]
