# Generated by Django 3.0.3 on 2020-05-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OgloszeniaKategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OgloszenieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=700)),
                ('opis', models.TextField()),
                ('img', models.ImageField(blank=True, default='static/assetss/img/backgrounds/img-2.jpg', null=True, upload_to='media')),
                ('kategoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ogloszenie', to='ogloszenia.OgloszeniaKategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Dodaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=250)),
                ('tresc', models.TextField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodaj', to='ogloszenia.OgloszeniaKategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('ogloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ogloszenia.OgloszenieDetail')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
