# Generated by Django 3.0.3 on 2020-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='komentarz',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nazwa',
        ),
    ]
