# Generated by Django 3.0.3 on 2020-05-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200503_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='komentarz',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='nazwa',
            new_name='name',
        ),
    ]
