# Generated by Django 3.0.3 on 2020-05-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200503_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='tresc',
        ),
    ]
