# Generated by Django 3.0.3 on 2020-05-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200503_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='imie',
            new_name='imię',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='tresc',
            new_name='treść',
        ),
    ]
