# Generated by Django 3.0.3 on 2020-05-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200503_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='treść',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='imię',
            new_name='name',
        ),
    ]
