# Generated by Django 3.0.3 on 2020-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_comment_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='img2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(default='static/img/backgrounds/img-2.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='imgglowne',
            field=models.ImageField(default='static/img/backgrounds/img-2.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='text3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='text4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
