# Generated by Django 3.0.3 on 2020-05-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randki', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dodaj',
        ),
    ]
