# Generated by Django 3.0.3 on 2020-05-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randki', '0002_delete_dodaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='randkadetail',
            name='plec',
            field=models.CharField(choices=[('Mężczyzna', 'Mężczyzna'), ('Kobieta', 'Kobieta'), ('Inna', 'Inna')], default='Mężczyzna', max_length=30),
        ),
    ]
