# Generated by Django 3.0.3 on 2020-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randki', '0003_randkadetail_plec'),
    ]

    operations = [
        migrations.AddField(
            model_name='randkadetail',
            name='miasto',
            field=models.CharField(default='', max_length=40),
        ),
    ]
