# Generated by Django 3.0.3 on 2020-05-06 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=500)),
                ('text1', models.TextField()),
                ('imgglowne', models.ImageField(default='static/img/backgrounds/img-2.jpg', upload_to='media')),
                ('title2', models.CharField(blank=True, max_length=500, null=True)),
                ('text2', models.TextField(blank=True, default='', null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title3', models.CharField(blank=True, max_length=500, null=True)),
                ('text3', models.TextField(blank=True, default='', null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title4', models.CharField(blank=True, max_length=500, null=True)),
                ('text4', models.TextField(blank=True, default='', null=True)),
                ('autor', models.CharField(default='', max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoradyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=200)),
                ('film', models.CharField(max_length=700)),
                ('zdjecie', models.ImageField(default='static/assets/img/backgrounds/img-2.jpg', upload_to='media')),
            ],
        ),
    ]
