# Generated by Django 3.0.3 on 2020-05-01 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porady',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(default='static/img/backgrounds/img-2.jpg', upload_to='media/porady')),
                ('www', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
