# Generated by Django 3.0.3 on 2020-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porady', '0003_poradyvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poradyvideo',
            name='zdjecie',
            field=models.ImageField(default='static/assets/img/backgrounds/img-2.jpg', upload_to='media'),
        ),
    ]
