# Generated by Django 3.0.3 on 2020-05-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porady', '0004_poradyvideo_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porady',
            name='img',
        ),
    ]
